version: "3.8"
services:
  base:
    image: analytics-data-science
    container_name: analytics-data-science-base
    
    build: 
      context: .
      dockerfile: ./Dockerfile
    
    volumes:
      - ./src:/app/src
      - ./transversal:/app/transversal
      - ./application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
      - ./requirements.txt:/app/requirements.txt
    
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
    
    env_file:
      - .env
    
    ports:
      - "8888:8888"